version: '3'

services:
  whoami:
    image: containous/whoami
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.middlewares.httpsupgrade.redirectscheme.scheme=https"

networks:
  web:
    external: true
