version: '3'

services:
  whoami:
    image: containous/whoami
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-http.entrypoints=http"
      - "traefik.http.routers.whoami-http.middlewares=https-redirect@file"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls=true"

networks:
  web:
    external: true
