version: '3'

services:
  whoami:
    image: containous/whoami
    restart: always
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.frontend.rule: Host:whoami.${DOMAIN}

networks:
  web:
    external: true
