version: '3'

services:
  app:
    image: traefik:1.7
    restart: always
    ports:
      - "${HTTP_PORT}:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ${IMAGE_DATA}/traefik/acme:/acme
      - ./auth-ca:/etc/ssl/auth-ca
    networks:
      - web
    environment:
      - CF_API_EMAIL
      - CF_API_KEY

networks:
  web:
    external: true
