version: '3'

services:
  app:
    image: traefik:1.7
    restart: always
    ports:
      - "${HTTP_PORT}:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ${IMAGE_DATA}/traefik/acme:/acme
    networks:
      - web

networks:
  web:
    external: true
