version: '3'

services:
  nginx:
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./content/home:/usr/share/nginx/html:ro
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.frontend.rule: Host:${DOMAIN}

networks:
  web:
    external: true
